# Generated by Django 5.1.4 on 2024-12-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_question_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='not_answered_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_correct_first',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
